import Nav from "@/app/components/Nav/Nav";
import Footer from "@/app/components/Footer/Footer";
import './globals.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#EDEEF0]">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
